[package]
name = "modsmodder"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.104"
notifica = "3.0.2"
popout = "0.1.1"
#native-dialog = "0.9.7"
rfd = "0.17.2"
slint = "1.17.1"

[dependencies.native-dialog]
version = "0.9.7"
features = ["windows_dpi_awareness", "windows_visual_styles"]

[build-dependencies]
slint-build = "1.17.1"

